/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        display: ['Geist', 'system-ui', 'sans-serif'],
        title: ['Instrument Serif', 'serif'],
        mono: ['Geist Mono', 'SF Mono', 'Monaco', 'Cascadia Code', 'Roboto Mono', 'Consolas', 'Courier New', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        stone: {
          50: "hsl(var(--stone-50))",
          100: "hsl(var(--stone-100))",
          200: "hsl(var(--stone-200))",
          300: "hsl(var(--stone-300))",
          400: "hsl(var(--stone-400))",
          500: "hsl(var(--stone-500))",
          600: "hsl(var(--stone-600))",
          700: "hsl(var(--stone-700))",
          800: "hsl(var(--stone-800))",
          900: "hsl(var(--stone-900))",
          950: "hsl(var(--stone-950))",
        },
        'tea-green': {
          DEFAULT: '#ccd5ae',
          50: '#f5f7ef',
          100: '#2d331a',
          200: '#5b6635',
          300: '#88994f',
          400: '#acbb7b',
          500: '#ccd5ae',
          600: '#d6debe',
          700: '#e1e6cf',
          800: '#ebeedf',
          900: '#f5f7ef',
        },
        'beige': {
          DEFAULT: '#e9edc9',
          50: '#fbfbf4',
          100: '#3d4216',
          200: '#79842c',
          300: '#b3c146',
          400: '#ced788',
          500: '#e9edc9',
          600: '#edf1d4',
          700: '#f2f4df',
          800: '#f6f8ea',
          900: '#fbfbf4',
        },
        'cornsilk': {
          DEFAULT: '#fefae0',
          50: '#fffef9',
          100: '#5d5103',
          200: '#baa206',
          300: '#f8dc27',
          400: '#fbeb84',
          500: '#fefae0',
          600: '#fefbe7',
          700: '#fefced',
          800: '#fffdf3',
          900: '#fffef9',
        },
        'papaya-whip': {
          DEFAULT: '#faedcd',
          50: '#fefbf5',
          100: '#533e08',
          200: '#a57b10',
          300: '#eab227',
          400: '#f2d079',
          500: '#faedcd',
          600: '#fbf1d6',
          700: '#fcf4e0',
          800: '#fdf8eb',
          900: '#fefbf5',
        },
        'buff': {
          DEFAULT: '#d4a373',
          50: '#f6ede3',
          100: '#32210f',
          200: '#64411f',
          300: '#96622e',
          400: '#c58341',
          500: '#d4a373',
          600: '#dcb68f',
          700: '#e5c8ab',
          800: '#eedac7',
          900: '#f6ede3',
        },
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
      },
      boxShadow: {
        'premium': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'premium-lg': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'premium-xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      },
      screens: {
        'xs': '475px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}